name: Lint
on:
  workflow_call:
jobs:
  build:
    name: Linters
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --config.platform=linux --config.architecture=x64

      - name: create .env
        run: cp .env.example .env

      - name: Generate Random ENCRYPTION_KEY
        run: |
          SECRET=$(openssl rand -hex 32)
          echo "ENCRYPTION_KEY=$SECRET" >> $GITHUB_ENV

      - name: Lint
        run: pnpm lint
